xpath_1337x = '//table/tbody/tr/td[1]/a[2]'
QUERIES = [
    {
        'url': 'https://1337x.to/user/FitGirl/',
        'id': 'FitGirl',
        'xpath': xpath_1337x,
        'block_external': True,
        'max_notif': 10,
    },
    {
        'url': 'https://1337x.to/user/DODI/',
        'id': 'DODI',
        'xpath': xpath_1337x,
        'block_external': True,
        'max_notif': 10,
        'active': False,
    },
    {
        'url': 'https://actualitte.com/thematique/35/chroniques',
        'id': 'livres',
        'xpath': '//a[contains(@class, "list-article_link") or contains(@class, "article-card_link")]/h2',
        'link_xpath': '..',
        'block_external': True,
        'update_delta': 8 * 3600,
        'active': False,
    },
    {
        'url': 'https://rutracker.org/forum/tracker.php?f=557',
        'id': 'classical',
        'xpath': '//div[contains(@class, "t-title")]/a',
        'block_external': True,
        'update_delta': 8 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.techspot.com/drivers/manufacturer/nvidia_geforce/',
        'id': 'geforce-drivers',
        'xpath': '//div[contains(@class, "title")]/a',
        'block_external': True,
        'update_delta': 16 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.intel.com/content/www/us/en/support/articles/000005489/wireless.html',
        'id': 'intel-wireless-drivers',
        'xpath': '//table[contains(@class, "icstable")]/tbody/tr[not(contains(@class, "icstablehead"))]/td/*/a',
        'block_external': True,
        'update_delta': 16 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.lexpressproperty.com/en/buy-mauritius/residential_land/riviere_noire-la_gaulette-la_preneuse-tamarin/?price_max=6%2C000%2C000&currency=MUR&filters%5Bland_unit%5D%5Beq%5D=m2',
        'id': 'land-west',
        'xpath': '//div[contains(@class, "card-row")]',
        'child_xpaths': [
            './/div[contains(@class, "title-holder")]/h2',
            './/address',
            './/div[contains(@class, "card-foot-price")]/strong/a',
        ],
        'link_xpath': './/a',
        'block_external': True,
        'update_delta': 4 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.facebook.com/iqonmauritius',
        'id': 'fb-iqon',
        'scroll_xpath': '//*[local-name()="image"]',
        'rel_xpath': '../../../../../../../../../../../../div[3]/div[1]',
        'link_xpath': '../../../../../../../../../../../../div[3]/div[2]/*/a',
        'update_delta': 4 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.nvidia.com/en-us/geforce/news/',
        'id': 'geforce-news',
        'xpath': '//div[contains(@class, "article-title-text")]/a',
        'block_external': True,
        'update_delta': 16 * 3600,
        'active': False,
    },
    {
        'url': 'https://www.facebook.com/marketplace/108433389181024/propertyforsale',
        'id': 'fb-properties',
        'scroll_xpath': '//img',
        'rel_xpath': '../../../../../../../div[2]/div',
        'scroll_group_attrs': ['width', 'height'],
        'link_xpath': '../../../../../../../..',
        'update_delta': 8 * 3600,
        'active': False,
    },
]
