name: Build Executables for Windows and Linux

on:
  push:
    branches:
      - main
      - exe
  pull_request:
    branches:
      - main

jobs:
  # Job for building Windows executable
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
        pip install -r requirements.txt

    # - name: Install Dependencies
    #   shell: cmd
    #   run: |
    #     set PLAYWRIGHT_BROWSERS_PATH=0
    #     playwright install webkit

    - name: Build Windows Executable
      run: |
        pyinstaller --onefile --name bodiez bodiez/main.py
        dir dist

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: bodiez-windows
        path: dist/bodiez.exe
