name: Build Executables for Windows and Linux

on:
  push:
    branches:
      - main
      - exe
  pull_request:
    branches:
      - main

jobs:
  # Job for building Linux executable
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
        pip install -r requirements.txt

    - name: Install Playwright Dependencies
      run: |
        python -m playwright install-deps

    - name: Install System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant-2-2 libgudev-1.0-0 \
          libsecret-1-0 libhyphen0 libgles2 libegl1 libxslt1.1 libevent-2.1-7 \
          libnotify4 libvpx7 libavif13 libicu70 || true

    - name: Install playwright browser
      run: |
        export PLAYWRIGHT_BROWSERS_PATH=0
        playwright install webkit

    - name: Build Linux Executable
      run: |
        pyinstaller --onefile --name bodiez bodiez/main.py
        ls dist/

    - name: Upload Linux Executable
      uses: actions/upload-artifact@v3
      with:
        name: bodiez-linux
        path: dist/bodiez

  # Job for building Windows executable
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
        pip install -r requirements.txt

    - name: Install playwright browser
      shell: cmd
      run: |
        set PLAYWRIGHT_BROWSERS_PATH=0
        playwright install webkit

    - name: Build Windows Executable
      run: |
        pyinstaller --onefile --name bodiez bodiez/main.py
        dir dist

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: bodiez-windows
        path: dist/bodiez.exe
